server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=test;trustServerCertificate=true
    username: sa
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect